version: '3'

networks:
  chatnet:
    driver: bridge

services:
  websocket-service:
    container_name: websocket_service
    build: .
    env_file: .env
    ports:
      - 8080:8080
    networks:
      - chatnet